# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('newspaper_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('newspaper_name', models.CharField(max_length=400)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=200)),
                ('black_ethnic', models.BooleanField()),
                ('spa_full_member', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_type', models.CharField(max_length=200)),
                ('owner_type_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='newspaper',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_db.Owner'),
        ),
    ]
