# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspaper',
            name='county',
        ),
        migrations.RemoveField(
            model_name='state',
            name='id',
        ),
        migrations.AddField(
            model_name='state',
            name='state_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
