# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='owner_id',
            field=models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.PROTECT, to='main_db.Owner'),
        ),
    ]
